go_library(
    name = "golang",
    srcs = [
        "constants.go",
        "message.go",
        "mini_table.go",
        "mini_table_field.go",
        "presence.go",
    ],
    cgo = 1,
    deps = [
        "//:mini_table_internal",  #keep
    ],
)
